apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-qa.yaml
  - use-configmap.yaml
  - service.yaml

configMapGenerator:
  - name: demo-config
    files:
      - application.properties