apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: demo-config
      containers:
        - name: springboot-demo
          args:
            - --spring.config.location=/etc/config/application.properties
          volumeMounts:
            - mountPath: /etc/config
              name: config